### ISSUE TITLE
Problem with login

### ISSUE THREAD

**Issue by SlaSerX** [Sjord/growatt_api_client#32]
Hello have any solutions i cant login

└> python3.8 -m growatt '****' '****'
Traceback (most recent call last):
  File "/home/slaserx/lab/growatt_api_client/growatt/__init__.py", line 71, in login
    result = self._back_success_response(response)
  File "/home/slaserx/lab/growatt_api_client/growatt/__init__.py", line 157, in _back_success_response
    raise GrowattApiError("Request failed: %s" % response)
growatt.GrowattApiError: Request failed: <Response [400]>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/slaserx/lab/growatt_api_client/growatt/__main__.py", line 9, in <module>
    api.login(username, password)
  File "/home/slaserx/lab/growatt_api_client/growatt/__init__.py", line 76, in login
    raise LoginError
growatt.LoginError

**Comment by Sjord** [comment]
Could you take a look at [Use newTwoLoginAPI to login by Sjord · Pull Request #31 · Sjord/growatt_api_client](https://github.com/Sjord/growatt_api_client/pull/31) and see if that helps?

**Comment by SlaSerX** [comment]
Yes I make all of this but still it's same :(

На вт, 26.07.2022 г., 23:10 ч. Sjoerd Langkemper ***@***.***>
написа:

**Comment by Keetmalin** [comment]
I'm a new user. I am also getting the same error
