### ISSUE TITLE
Log in problems - again

### ISSUE THREAD

**Issue by roger-stedman** [Sjord/growatt_api_client#37]
Apologies - Have downloaded and installed.  Updated as per advice in issue 32 and 30.  Have tried all versions of server url (growatt-api.com, growatt-us.com and growatt.com - all with both https:// and http://) but I am still getting failed login. Any advice greatly received.  I am trying to use my pi to create a power switch that turns on when the PV panels are generating sufficient power (to charge my EV)

(venv) rstedman@raspberrypi:~/growatt_api_client $ venv/bin/python3.9 -m growatt '{my-username}' '{my-password}'
Traceback (most recent call last):
  File "/home/rstedman/growatt_api_client/growatt/__init__.py", line 71, in login
    result = self._back_success_response(response)
  File "/home/rstedman/growatt_api_client/growatt/__init__.py", line 157, in _back_success_response
    raise GrowattApiError("Request failed: %s" % response)
growatt.GrowattApiError: Request failed: <Response [400]>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rstedman/growatt_api_client/growatt/__main__.py", line 9, in <module>
    api.login(username, password)
  File "/home/rstedman/growatt_api_client/growatt/__init__.py", line 76, in login
    raise LoginError
growatt.LoginError

**Comment by olliebu** [comment]
I receive the same error message. Help is also much appreciated.

**Comment by Yogi4301** [comment]
Hello,
from today on no login is possible anymore - I always get the following error:

Traceback (most recent call last):
  File "/home/pi/growatt_api_client/growatt/__init__.py", line 71, in login
    result = self._back_success_response(response)
  File "/home/pi/growatt_api_client/growatt/__init__.py", line 188, in _back_success_response
    raise GrowattApiError("Request failed: %s" % response)
growatt.GrowattApiError: Request failed: <Response [403]>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/growatt_api_client/growatt/__main__.py", line 19, in <module>
    api.login(username, password)
  File "/home/pi/growatt_api_client/growatt/__init__.py", line 76, in login
    raise LoginError
growatt.LoginError

**Comment by xtendtech** [comment]
Not working . I gave user id and password. Any ome knows if we can get the token? growatt support doesnt know what i am talking about

**Comment by olliebu** [comment]
The login is working for me now with newLogin() at "https://server.growatt.com". But I also never got a reply from Growatt support. I don't have any hopes in them that they will ever reply to my query.

**Comment by xtendtech** [comment]
> The login is working for me now with newLogin() at "https://server.growatt.com". But I also never got a reply from Growatt support. I don't have any hopes in them that they will ever reply to my query.

is it using python code? can you share the code?

**Comment by olliebu** [comment]
> > The login is working for me now with newLogin() at "https://server.growatt.com". But I also never got a reply from Growatt support. I don't have any hopes in them that they will ever reply to my query.
> 
> is it using python code? can you share the code?

I am using this class for a successful connection [growatt.py](https://github.com/olliebu/smartwater/blob/49dd8b13729bf3d6ef6e199794163316249aa943/growatt.py)

**Comment by olliebu** [comment]
For me the request still works without Error-Response.
